# Generated by Django 4.1.1 on 2022-11-19 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinariaAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cirugias',
            options={'verbose_name': 'nombre paciente', 'verbose_name_plural': 'nombre pacientes'},
        ),
        migrations.AlterModelOptions(
            name='consulta',
            options={'verbose_name': 'nombre paciente', 'verbose_name_plural': 'nombre pacientes'},
        ),
        migrations.AlterModelOptions(
            name='esteticaveterinaria',
            options={'verbose_name': 'nombre paciente', 'verbose_name_plural': 'nombre pacientes'},
        ),
        migrations.AlterModelOptions(
            name='ingresodueño',
            options={'verbose_name': 'Nombre dueño', 'verbose_name_plural': 'Nombre dueños'},
        ),
        migrations.AlterModelOptions(
            name='ingresomascota',
            options={'verbose_name': 'Nombre mascota', 'verbose_name_plural': 'Nombre mascotas'},
        ),
        migrations.AlterModelOptions(
            name='vacunas',
            options={'verbose_name': 'nombre paciente', 'verbose_name_plural': 'nombre pacientes'},
        ),
    ]
