# Generated by Django 4.1.1 on 2022-11-20 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinariaAPP', '0003_rename_ingresodueño_ingresodueno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingresodueno',
            old_name='nombre_Dueño',
            new_name='nombre',
        ),
    ]
