# Generated by Django 4.1.1 on 2022-11-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinariaAPP', '0006_rename_fechaatencion_cirugias_fecha_atencion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esteticaveterinaria',
            name='fecha_atencion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
