# Generated by Django 4.1.1 on 2022-11-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinariaAPP', '0007_alter_esteticaveterinaria_fecha_atencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esteticaveterinaria',
            name='fecha_atencion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
